spring.datasource.url=jdbc:postgresql://db:5432/academy_tracker
spring.datasource.username=academy_user
spring.datasource.password=academy_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect