services:

  db:
    image: postgres:15-alpine
    container_name: academy_db
    environment:
      POSTGRES_DB: academy_tracker
      POSTGRES_USER: vladi
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - academy-network


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: academy_backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/academy_tracker
      - SPRING_DATASOURCE_USERNAME=vladi
      - SPRING_DATASOURCE_PASSWORD=password123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
    networks:
      - academy-network


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: academy_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - academy-network

volumes:
  pgdata:

networks:
  academy-network:
    driver: bridge